language: go
dist: trusty
sudo: required

go:
  - 1.7.3

ruby:
  - 2.2.5

env:
  matrix:
    - BUILD_ARGS="GOOS=linux,GOARCH=amd64,DEBARCH=amd64"
    - BUILD_ARGS="GOOS=linux,GOARCH=arm,DEBARCH=armhf,GOARM=7"
  global:
    - RELEASE_KEY_ID: B6AD190A
    - secure: clbfKHLDuPNPS4Cpu6h/ub9+LtW76oOjBlo3e462f3W8lQg/u9ot6Zf+zjWRwZrq/Ja1XzMq/RAu5hy12NwsygRFeTDQeuBRKnLpZBoCQ6JLQMsyQhaQCgdSDSZAXO45j37e+iiW2YwHefYd9tCUzHdL5p8y0jDju5pEVasstxSFJ2zj3rnWn7saweMoGrxhweCtIODUic4n/8WgmizGUKywb2hXQoYxj+FSIH9Q1jKOL0rrTyG3gwhNhUxQPoiBVsvyqKBPgXh8wrZ79QMHkADY1QxT6948TQ61M+j/s8RpjWLom3/Lr+PkxW25RQtahu3pPWx99pO0tk5C88b6Kv8csdr8jRe7EoMeQt5TnMPHT183uDpHA/1efrqCxu6XHz4Gu/GqOtdQajG2HOGoKRk7jmtjtSrlieE0SRzSpFQkg2uzEi8GozxvtMGE97Gow2pjyvY/k0BvOTNKGi2FUuc0nEYFnwsc4nfYlPxUnfhdhrjHJZdHXoueiPzBkKSFNQqQBEJdWBxmakVhjVJG8whD6SRx/WDbFaI+vfS4nEnNcHU8HptNJ169TUYTce033fSF3L9iElqrbPlmcOVrmcO86BBtOdV1pKGzZ3q6wsz3rc+hPg6l9//dENJCXHfMrtgp1KD5IF1C1nb/F6leiRFFlJlTYsRayjpgD5RkVnQ=
    - secure: fQr3jiaawK8J664u6s+vbEeF6RC54M6oSSzeCGb0BDtSwu8ZnRayJ56VT1j6XyjF6zPsIKwWiimkc5KH9+7LUODPVJ8Rc+3G0O7feBz6z5zBc6+zs0mi8l9F1+30TsUsaydWwNEzLXfsNCB72mruB0CfF4J35Havl/zV52IB6BADDDSbhXf7vILIN1y/5gZxId0GjZA4QHyiuipvJOEEIjmdZTSFy3bl8Ymga8DrnA/EkqUM9PP5a4vOz2XEUAmkoGcwPsc2/C8KxZNq6IK+qDy768TYsKj9d57F1Eje6kAiLdMqz2zXh8nC///+VKxmh0cEDby6HvfmYPF60fe/VnB+uzOdh418rrvwVIPUSooR1YwFWKSGNvfQP+sDRdvsPCvu6soIVRrEc3pfbJDK4OTBXWmttayR/QlJnALgenn38TX3lwBoCV6tyqYbTWpKJxc2lfvjy5UAD3UxL8yItp1OCIvvDhOrmbkJAJvKODnuPpKT5jcc696AHHl760zfmierHir/r5JSoZeA+rLT7vAEokPk8LbmOiGLVvuFxEzyOGQSOZ3pyeTEM3wFxtJuoe3MiAhaQe0ch2E6Qi7Rd+5DRZTJZf96qZ948QkicyHtwqlVeJKf+mT0rIPWPMc8cJR+tneNFln+KR2oHV0mE9nDsyfhXC18KZLBSIdBtPw=

before_install:
- openssl aes-256-cbc -K $encrypted_f87500241524_key -iv $encrypted_f87500241524_iv
  -in signing.key.enc -out signing.key -d
- sudo apt-get install dh-make --fix-missing -y

install:
  - rvm use 2.2.5
  - gem install deb-s3 --no-rdoc --no-ri
  - gpg --import signing.key

script: "scripts/build.sh $BUILD_ARGS"

deploy:
  provider: script
  script: "scripts/deploy.sh $BUILD_ARGS"
  on:
    tags: true